care/facility/urls.py
from django.urls import path

from .views import (
    FacilityCreation,
    FacilityCapacityCreation,
    FacilitiesView,
    FacilityView,
    FacilityUpdation,
    FacilityCapacityUpdation,
    DoctorCountCreation,
    DoctorCountUpdation,
)

app_name = "facility"
urlpatterns = [
    path("create/", FacilityCreation.as_view(), name="facility-create"),
    path("", FacilitiesView.as_view(), name="facilities-view"),
    path("<int:pk>", FacilityView.as_view(), name="facility-view"),
    path("<int:pk>/update", FacilityUpdation.as_view(), name="facility-update"),
    path(
        "<int:pk>/capacity/add/",
        FacilityCapacityCreation.as_view(),
        name="facility-capacity-create",
    ),
    path(
        "<int:fpk>/capacity/<int:cpk>/",
        FacilityCapacityUpdation.as_view(),
        name="facility-capacity-update",
    ),
    path(
        "<int:pk>/doctorcount/add/",
        DoctorCountCreation.as_view(),
        name="facility-doctor-count-create",
    ),
    path(
        "<int:fpk>/doctorcount/<int:cpk>/",
        DoctorCountUpdation.as_view(),
        name="facility-doctor-count-update",
    ),
]

care/users/urls.py
from django.urls import path

# from care.users.views import (
#     user_detail_view,
#     user_redirect_view,
#     user_update_view,
# )

from django.contrib.auth.views import LogoutView
from .views import SignupView, SinginView

app_name = "users"
urlpatterns = [
    # path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
    path(
        "signup/volunteer/",
        SignupView.as_view(),
        {"type": 20, "name": "Volunteer"},
        name="signup-volunteer",
    ),
    path(
        "signup/doctor/",
        SignupView.as_view(),
        {"type": 5, "name": "Doctor"},
        name="signup-doctor",
    ),
    path(
        "signup/staff/",
        SignupView.as_view(),
        {"type": 10, "name": "Hospital Administrator"},
        name="signup-staff",
    ),
    path("signin/", SinginView.as_view(), name="signin"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from config import api_router

schema_view = get_schema_view(
    openapi.Info(
        title="Care API",
        default_version="v1",
        description="Api Documentation for Care",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="-"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "ksdma/", TemplateView.as_view(template_name="pages/ksdma.html"), name="ksdma"
    ),
    # API Docs
    url(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    url(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    url(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    # Rest API
    path("api/v1/auth/login/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path(
        "api/v1/auth/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"
    ),
    path("api/v1/auth/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("care.users.urls", namespace="users")),
    # path("accounts/", include("allauth.urls")),
    path("facility/", include("care.facility.urls", namespace="facility")),
    # RESTful APIs
    path("api/v1/", include(api_router.urlpatterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

care/facility/forms.py
from django.forms import ModelForm

from .models import Facility, FacilityCapacity, HospitalDoctors


class FacilityCreationForm(ModelForm):
    class Meta:
        model = Facility
        fields = ["name", "district", "address", "oxygen_capacity", "phone_number"]
        labels = {"name": "Enter the name of your hospital", "district": "Pick your District",
                  "address": "Enter Hospital Address",
                  "phone_number": "Enter emergency contact number of your hospital","oxygen_capacity":"Enter the total oxygen capacity of your hospital (in litres)"}


class FacilityCapacityCreationForm(ModelForm):
    class Meta:
        model = FacilityCapacity
        fields = ["room_type", "total_capacity", "current_capacity"]
        labels = {"room_type": "Bed Type", "total_capacity": "Total Capacity",
                  "current_capacity": "Currently Occupied"}


class DoctorsCountCreationForm(ModelForm):
    class Meta:
        model = HospitalDoctors
        fields = ["area", "count"]
        labels = {"area": "Area of specialization"}

care/facility/views.py
import logging

from django.shortcuts import render, redirect
from django.views import View
from django.http import HttpResponseRedirect
from django.db import IntegrityError
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.conf import settings

from .forms import (
    FacilityCreationForm,
    FacilityCapacityCreationForm,
    DoctorsCountCreationForm,
)
from .models import Facility, FacilityCapacity, HospitalDoctors


class StaffRequiredMixin:
    def dispatch(self, request, *args, **kwargs):
        if request.user.user_type == settings.STAFF_ACCOUNT_TYPE:
            return super().dispatch(request, *args, **kwargs)
        else:
            return redirect_to_login(self.request.get_full_path())


class FacilitiesView(LoginRequiredMixin, StaffRequiredMixin, View):

    template = "facility/facilities_view.html"

    def get(self, request):
        try:
            current_user = request.user
            data = Facility.objects.filter(created_by=current_user)
            return render(request, self.template, {"data": data})
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")


class FacilityView(LoginRequiredMixin, StaffRequiredMixin, View):

    template = "facility/facility_view.html"

    def get(self, request, pk):
        try:
            current_user = request.user
            facility_obj = Facility.objects.get(id=pk, created_by=current_user)
            capacities = FacilityCapacity.objects.filter(facility=facility_obj)
            doctor_counts = HospitalDoctors.objects.filter(facility=facility_obj)
            return render(
                request,
                self.template,
                {
                    "capacities": capacities,
                    "doctor_counts": doctor_counts,
                    "facility": facility_obj,
                },
            )
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")


class FacilityCreation(LoginRequiredMixin, StaffRequiredMixin, View):

    form_class = FacilityCreationForm
    template = "facility/facility_creation.html"

    def get(self, request):
        try:
            form = self.form_class()
            return render(request, self.template, {"form": form})
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")

    def post(self, request):
        try:
            data = request.POST
            form = self.form_class(data)
            if form.is_valid():
                facility_obj = form.save(commit=False)
                facility_obj.created_by = request.user
                facility_obj.facility_type = 2
                facility_obj.save()
                return redirect("facility:facility-capacity-create", facility_obj.id)
            return render(request, self.template, {"form": form})
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")


class FacilityUpdation(LoginRequiredMixin, StaffRequiredMixin, View):

    form_class = FacilityCreationForm
    template = "facility/facility_updation.html"

    def get(self, request, pk):
        try:
            current_user = request.user
            facility_obj = Facility.objects.get(id=pk, created_by=current_user)
            form = self.form_class(instance=facility_obj)
            return render(request, self.template, {"form": form})
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")

    def post(self, request, pk):
        try:
            current_user = request.user
            facility_obj = Facility.objects.get(id=pk, created_by=current_user)
            data = request.POST
            form = self.form_class(data, instance=facility_obj)
            if form.is_valid():
                form.save()
                return redirect("facility:facility-view", facility_obj.id)
            return render(request, self.template, {"form": form})
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")


class FacilityCapacityCreation(LoginRequiredMixin, StaffRequiredMixin, View):
    form_class = FacilityCapacityCreationForm
    template = "facility/facility_capacity_creation.html"

    def get(self, request, pk):
        try:
            form = self.form_class()
            current_user = request.user
            facility_obj = Facility.objects.get(id=pk, created_by=current_user)
            return render(
                request, self.template, {"form": form, "facility": facility_obj}
            )
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")

    def post(self, request, pk):
        try:
            data = request.POST
            form = self.form_class(data)
            facility_obj = Facility.objects.get(id=pk)
            validation_error = False
            duplicate = False
            if form.is_valid():
                if form.cleaned_data.get('total_capacity') >= form.cleaned_data.get('current_capacity'):
                    duplicate = False
                    facility_capacity_obj = form.save(commit=False)
                    facility_obj = Facility.objects.get(id=pk)
                    facility_capacity_obj.facility = facility_obj
                    try:
                        facility_capacity_obj.save()
                        if "addmore" in data:
                            return redirect(
                                "facility:facility-capacity-create", facility_obj.id
                            )
                        else:
                            return redirect(
                                "facility:facility-doctor-count-create", facility_obj.id
                            )
                    except IntegrityError:
                        duplicate = True
                else:
                    validation_error = True
            return render(
                request,
                self.template,
                {"form": form, "facility": facility_obj, "duplicate": duplicate, "validation_error": validation_error},
            )
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")


class FacilityCapacityUpdation(LoginRequiredMixin, StaffRequiredMixin, View):
    form_class = FacilityCapacityCreationForm
    template = "facility/facility_capacity_updation.html"

    def get(self, request, fpk, cpk):
        try:
            current_user = request.user
            facility_obj = Facility.objects.get(id=fpk, created_by=current_user)
            capacity_obj = FacilityCapacity.objects.get(id=cpk, facility=facility_obj)
            form = self.form_class(instance=capacity_obj)
            return render(
                request, self.template, {"form": form, "facility": facility_obj}
            )
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")

    def post(self, request, fpk, cpk):
        try:
            data = request.POST
            current_user = request.user
            facility_obj = Facility.objects.get(id=fpk, created_by=current_user)
            capacity_obj = FacilityCapacity.objects.get(id=cpk, facility=facility_obj)
            form = self.form_class(data, instance=capacity_obj)
            duplicate = False
            validation_error = False
            if form.is_valid():
                if form.cleaned_data.get('total_capacity') >= form.cleaned_data.get('current_capacity'):
                    try:
                        form.save()
                        return redirect("facility:facility-view", facility_obj.id)
                    except IntegrityError:
                        duplicate = True
                else:
                    validation_error = True
            return render(
                request, self.template, {"form": form, "duplicate": duplicate,
                                         "validation_error": validation_error, "facility": facility_obj}
            )
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")


class DoctorCountCreation(LoginRequiredMixin, StaffRequiredMixin, View):
    form_class = DoctorsCountCreationForm
    template = "facility/facility_doctor_count_creation.html"

    def get(self, request, pk):
        try:
            form = self.form_class()
            current_user = request.user
            facility_obj = Facility.objects.get(id=pk, created_by=current_user)
            return render(
                request, self.template, {"form": form, "facility": facility_obj}
            )
        except Exception as e:
            logging.error(e)
            return HttpResponseRedirect("/500")

    def post(self, request, pk):
        try:
            data = request.POST
            form = self.form_class(data)
            if form.is_valid():
                duplicate = False
                facility_capacity_obj = form.save(commit=False)
                facility_obj = Facility.objects.get(id=pk)
                facility_capacity_obj.facility = facility_obj
                try:
                    facility_capacity_obj.save()
                    if "addmore" in data:
                        return redirect(
                            "facility:facility-doctor-count-create", facility_obj.id
                        )
                    else:
                        return redirect("facility:facility-view", facility_obj.id)
                except IntegrityError:
                    duplicate = True
            return render(
                request,
                self.template,
                {"form": form, "facility": facility_obj, "duplicate": duplicate},
            )
        except Exception as e:
            logging.error(e)

care/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated, IsAdminUser


from care.users.api.serializers import UserSerializer

User = get_user_model()


class UserViewSet(viewsets.ModelViewSet):
    """
    A viewset for viewing and manipulating user instances.
    """

    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_permissions(self):
        if self.request.method == "POST":
            self.permission_classes = ()  # allows signup
        else:
            self.permission_classes = (IsAuthenticated,)
        return super().get_permissions()

    def get_queryset(self):
        if self.request.method == "DELETE" or self.request.method == "PUT":
            return self.queryset.filter(id=self.request.user.id)
        else:
            return self.queryset

    @action(detail=False, methods=["GET"])
    def getcurrentuser(self, request):
        return Response(
            status=status.HTTP_200_OK,
            data=self.serializer_class(request.user, context={"request": request}).data,
        )

care/templates/pages/home.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}


<section class="mt-4 max-w-lg ">
  <h1 class="text-3xl font-bold text-center"> Corona Safe Network </h1>
    {% if request.user.is_authenticated %}
    <p class="text-lg mt-1 text-gray-700 text-justify ">You  have successfully logged in to the corona care network.
    <br><br>
    The next step is to register your Hospital into the corona care network and enter details about total capacity of regular beds, ICU beds, and ventilators.
    <br><br>
    Once you connect your hospital to the corona care network, You will be able to view hospital details using the view hospital button.</p>
      {% if request.user.user_type == settings.STAFF_ACCOUNT_TYPE %}
      <div class="mt-4 flex flex-col">
        <div class="flex flex-col">
          <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'facility:facility-create' %}">{% trans "Add Hospital" %}</a>
        </div>
        <div class="flex flex-col">
          <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'facility:facilities-view' %}">{% trans "View Hospitals" %}</a>
        </div>
      </div>
      {% endif %}

    {% else %}
      <p class="text-lg mt-1 text-gray-700 text-justify "> Our Goal is to defend the Healthcare system of Kerala from overloading beyond capacity.
      </p>

    <div>
      <div class="mt-4 flex flex-col">
        <!--<div class="flex flex-col">
          <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'users:signup-volunteer' %}">{% trans "Volunteer Sign Up" %}</a>
        </div>
        <div class="flex flex-col">
          <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'users:signup-doctor' %}">{% trans "Doctor Sign Up" %}</a>
        </div>-->
      <div class="flex flex-col">
        <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'ksdma' %}">{% trans "KSDMA: Hospital Registration" %}</a>
        </div>
      <div class="flex flex-col">
        <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="https://alpha.care.coronasafe.network/ambulance">{% trans "Register An Ambulance" %}</a>
        </div>
      <div class="flex flex-col">
        <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'users:signin' %}">{% trans "Login to Corona Safe Network" %}</a>
        </div>
      </div
    </div>
    {% endif %}

</section>

{% endblock content %}

care/templates/pages/ksdma.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
<section class="max-w-lg">
  <h1 class="text-3xl font-bold text-center"> Corona Safe Network </h1>
  <p class="text-lg mt-1 text-gray-700 text-justify "> Our Goal is to defend the Healthcare system of Kerala from overloading beyond capacity.
  <br><br>
  For this to happen, the Chief Minister's Office needs access to the live capacity utilisation of the healthcare system against the total capacity.
  <br><br>
  Corona Care is a tool designed for hospital administrators to send the most up-to-date information in a real-time basis to CMO through the Control Room setup by State Disaster Management Authority.
  <br><br>
  This form is made on request of Kerala State Disaster Management Authority for gathering information of private hospitals as ordered vide <a href="https://drive.google.com/file/d/1CIK_h-cHRzX3qfWG1CYDRpageffGDgtE/view?usp=sharing" class="care-secondary-color">GO (Ms) No 48/2020/GAD dated 21-3-2020</a>.
  {% if request.user.is_authenticated %}
    {% if request.user.user_type == settings.STAFF_ACCOUNT_TYPE %}
    <div class="mt-4 flex flex-col">
      <div class="flex flex-col">
        <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'facility:facility-create' %}">{% trans "Add Hospital" %}</a>
      </div>
      <div class="flex flex-col">
        <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'facility:facilities-view' %}">{% trans "View Hospitals" %}</a>
      </div>
    </div>
    {% endif %}

  {% else %}

  <div>
    <div class="mt-4 flex flex-col">
      <!--<div class="flex flex-col">
        <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'users:signup-volunteer' %}">{% trans "Volunteer Sign Up" %}</a>
      </div>
      <div class="flex flex-col">
        <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'users:signup-doctor' %}">{% trans "Doctor Sign Up" %}</a>
      </div>-->
    <div class="flex flex-col">
      <a id="sign-up-link" class="py-6 mt-4 bg-white rounded-md shadow border border-grey-500 inline-flex items-center justify-center whitespace-no-wrap text-sm font-semibold rounded cursor-pointer hover:bg-gray-300 h4" href="{% url 'users:signup-staff' %}">{% trans "Sign Up As Hospital Administrator" %}</a>
      </div>
    </div
  </div>
  {% endif %}

</section>
{% endblock content %}