care/facility/urls.py
from django.urls import path

from .views import (
    FacilityCreation,
    FacilityCapacityCreation,
    FacilitiesView,
    FacilityView,
    FacilityUpdation,
    FacilityCapacityUpdation,
    DoctorCountCreation,
    DoctorCountUpdation,
)

app_name = "facility"
urlpatterns = [
    path("create/", FacilityCreation.as_view(), name="facility-create"),
    path("", FacilitiesView.as_view(), name="facilities-view"),
    path("<int:pk>", FacilityView.as_view(), name="facility-view"),
    path("<int:pk>/update", FacilityUpdation.as_view(), name="facility-update"),
    path(
        "<int:pk>/capacity/add/",
        FacilityCapacityCreation.as_view(),
        name="facility-capacity-create",
    ),
    path(
        "<int:fpk>/capacity/<int:cpk>/",
        FacilityCapacityUpdation.as_view(),
        name="facility-capacity-update",
    ),
    path(
        "<int:pk>/doctorcount/add/",
        DoctorCountCreation.as_view(),
        name="facility-doctor-count-create",
    ),
    path(
        "<int:fpk>/doctorcount/<int:cpk>/",
        DoctorCountUpdation.as_view(),
        name="facility-doctor-count-update",
    ),
]

care/users/urls.py
from django.urls import path

# from care.users.views import (
#     user_detail_view,
#     user_redirect_view,
#     user_update_view,
# )

from django.contrib.auth.views import LogoutView
from .views import SignupView, SinginView

app_name = "users"
urlpatterns = [
    # path("~redirect/", view=user_redirect_view, name="redirect"),
    # path("~update/", view=user_update_view, name="update"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
    path(
        "signup/volunteer/",
        SignupView.as_view(),
        {"type": 20, "name": "Volunteer"},
        name="signup-volunteer",
    ),
    path(
        "signup/doctor/",
        SignupView.as_view(),
        {"type": 5, "name": "Doctor"},
        name="signup-doctor",
    ),
    path(
        "signup/staff/",
        SignupView.as_view(),
        {"type": 10, "name": "Hospital Administrator"},
        name="signup-staff",
    ),
    path("signin/", SinginView.as_view(), name="signin"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from config import api_router

schema_view = get_schema_view(
    openapi.Info(
        title="Care API",
        default_version="v1",
        description="Api Documentation for Care",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="-"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "ksdma/", TemplateView.as_view(template_name="pages/ksdma.html"), name="ksdma"
    ),
    # API Docs
    url(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    url(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    url(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    # Rest API
    path("api/v1/auth/login/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path(
        "api/v1/auth/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"
    ),
    path("api/v1/auth/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("care.users.urls", namespace="users")),
    # path("accounts/", include("allauth.urls")),
    path("facility/", include("care.facility.urls", namespace="facility")),
    # RESTful APIs
    path("api/v1/", include(api_router.urlpatterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

care/facility/models/facility.py
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
from django.core.validators import RegexValidator
from django.db import models
from location_field.models.spatial import LocationField

from care.users.models import GENDER_CHOICES, DISTRICT_CHOICES

User = get_user_model()


class SoftDeleteManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(deleted=False)


class FacilityBaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)

    objects = SoftDeleteManager()

    class Meta:
        abstract = True

    def delete(self):
        self.deleted = True
        self.save()


# Facility Model Start

ROOM_TYPES = [
    (0, "Total"),
    (1, "Normal"),
    (2, "Hostel"),
    (10, "ICU"),
    (20, "Ventilator"),
]

FACILITY_TYPES = [(1, "Educational Inst"), (2, "Hospital"), (3, "Other")]

DOCTOR_TYPES = [
    (1, "General Medicine"),
    (2, "Pulmonology"),
    (3, "Critical Care"),
    (4, "Paediatrics"),
    (5, "Other Speciality"),
]

AMBULANCE_TYPES = [(1, "Basic"), (2, "Cardiac"), (3, "Hearse")]

phone_number_regex = RegexValidator(
    regex="^((\+91|91|0)[\- ]{0,1})?[456789]\d{9}$",
    message="Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>",
    code="invalid_mobile",
)


class Facility(FacilityBaseModel):
    name = models.CharField(max_length=1000, blank=False, null=False)
    is_active = models.BooleanField(default=True)
    verified = models.BooleanField(default=False)
    district = models.IntegerField(choices=DISTRICT_CHOICES, blank=False)
    facility_type = models.IntegerField(choices=FACILITY_TYPES)
    address = models.TextField()
    location = LocationField(based_fields=["address"], zoom=7, blank=True, null=True)
    oxygen_capacity = models.IntegerField(default=0)
    phone_number = models.CharField(
        max_length=14, blank=True, validators=[phone_number_regex]
    )
    corona_testing = models.BooleanField(default=False)
    created_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return f"{self.name}, {DISTRICT_CHOICES[self.district - 1][1]}"

    class Meta:
        verbose_name_plural = "Facilities"


class HospitalDoctors(FacilityBaseModel):
    facility = models.ForeignKey(
        "Facility", on_delete=models.CASCADE, null=False, blank=False
    )
    area = models.IntegerField(choices=DOCTOR_TYPES)
    count = models.IntegerField()

    def __str__(self):
        return str(self.facility) + str(self.count)

    class Meta:
        unique_together = ["facility", "area", "deleted"]


class FacilityCapacity(FacilityBaseModel):
    facility = models.ForeignKey(
        "Facility", on_delete=models.CASCADE, null=False, blank=False
    )
    room_type = models.IntegerField(choices=ROOM_TYPES)
    total_capacity = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    current_capacity = models.IntegerField(default=0, validators=[MinValueValidator(0)])

    class Meta:
        unique_together = ["facility", "room_type", "deleted"]


class FacilityStaff(FacilityBaseModel):
    facility = models.ForeignKey(
        "Facility", on_delete=models.CASCADE, null=False, blank=False
    )
    staff = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return str(self.staff) + " for facility " + str(self.facility)


class FacilityVolunteer(FacilityBaseModel):
    facility = models.ForeignKey(
        "Facility", on_delete=models.CASCADE, null=False, blank=False
    )
    volunteer = models.ForeignKey(
        User, on_delete=models.CASCADE, null=False, blank=False
    )

    def __str__(self):
        return str(self.volunteer) + " for facility " + str(self.facility)


# Facility Model End


# Building Model Start


class Building(FacilityBaseModel):
    facility = models.ForeignKey(
        "Facility", on_delete=models.CASCADE, null=False, blank=False
    )
    name = models.CharField(max_length=1000)
    num_rooms = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    num_floors = models.IntegerField(validators=[MinValueValidator(0)], default=0)

    def __str__(self):
        return self.name + " under " + str(self.facility)


# Building Model End


# Room Model Start


class Room(FacilityBaseModel):
    building = models.ForeignKey(
        "Building", on_delete=models.CASCADE, null=False, blank=False
    )
    num = models.CharField(max_length=1000)
    floor = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    beds_capacity = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    occupied_beds = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    room_type = models.IntegerField(choices=ROOM_TYPES)

    def __str__(self):
        return self.num + " under " + str(self.building)


class StaffRoomAllocation(FacilityBaseModel):
    staff = models.ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return str(self.staff) + " Allocated For " + str(self.room)


# Room Model End

# Inventory Model Start


class InventoryItem(FacilityBaseModel):
    name = models.CharField(max_length=1000)
    description = models.TextField()
    minimum_stock = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    unit = models.CharField(max_length=20)

    def __str__(self):
        return (
            self.name
            + " with unit "
            + self.unit
            + " with minimum stock "
            + str(self.minimum_stock)
        )


class Inventory(FacilityBaseModel):
    facility = models.ForeignKey(
        "Facility", on_delete=models.CASCADE, null=False, blank=False
    )
    item = models.ForeignKey("InventoryItem", on_delete=models.CASCADE)
    quantitiy = models.IntegerField(validators=[MinValueValidator(0)], default=0)

    def __str__(self):
        return (
            self.item.name
            + " : "
            + str(self.quantitiy)
            + " "
            + self.item.unit
            + " in "
            + str(self.facility)
        )

    class Meta:
        verbose_name_plural = "Inventories"


class InventoryLog(FacilityBaseModel):
    inventory = models.ForeignKey("Inventory", on_delete=models.CASCADE)
    updated_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True
    )
    prev_count = models.IntegerField(validators=[MinValueValidator(0)], default=0)
    new_count = models.IntegerField(validators=[MinValueValidator(0)], default=0)

    def __str__(self):
        return (
            "Item "
            + str(self.inventory)
            + " Updated from "
            + str(self.prev_count)
            + " to "
            + str(self.new_count)
            + " updated by "
            + str(self.updated_by)
        )


# Inventory Model End


class Ambulance(FacilityBaseModel):
    vehicle_number_regex = RegexValidator(
        regex="^[A-Z]{2}[0-9]{1,2}[A-Z]{1,2}[0-9]{1,4}$",
        message="Please Enter the vehicle number in all uppercase without spaces, eg: KL13AB1234",
        code="invalid_vehicle_number",
    )
    INSURANCE_YEAR_CHOICES = ((2020, 2020), (2021, 2021), (2022, 2022))

    vehicle_number = models.CharField(
        max_length=20, validators=[vehicle_number_regex], unique=True, db_index=True
    )

    owner_name = models.CharField(max_length=255)
    owner_phone_number = models.CharField(
        max_length=14, validators=[phone_number_regex]
    )
    owner_is_smart_phone = models.BooleanField(default=True)

    primary_district = models.IntegerField(choices=DISTRICT_CHOICES, blank=False)
    secondary_district = models.IntegerField(
        choices=DISTRICT_CHOICES, blank=True, null=True
    )
    third_district = models.IntegerField(
        choices=DISTRICT_CHOICES, blank=True, null=True
    )

    has_oxygen = models.BooleanField()
    has_ventilator = models.BooleanField()
    has_suction_machine = models.BooleanField()
    has_defibrillator = models.BooleanField()

    insurance_valid_till_year = models.IntegerField(choices=INSURANCE_YEAR_CHOICES)

    ambulance_type = models.IntegerField(
        choices=AMBULANCE_TYPES, blank=False, default=1
    )

    @property
    def drivers(self):
        return self.ambulancedriver_set.filter(deleted=False)

    def __str__(self):
        return f"Ambulance - {self.owner_name}({self.owner_phone_number})"


class AmbulanceDriver(FacilityBaseModel):
    ambulance = models.ForeignKey(Ambulance, on_delete=models.CASCADE)

    name = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=14, validators=[phone_number_regex])
    is_smart_phone = models.BooleanField()

    def __str__(self):
        return f"Driver: {self.name}({self.phone_number})"

care/facility/forms.py
from django.forms import ModelForm

from .models import Facility, FacilityCapacity, HospitalDoctors


class FacilityCreationForm(ModelForm):
    class Meta:
        model = Facility
        fields = ["name", "district", "address", "oxygen_capacity", "phone_number"]
        labels = {"name": "Enter the name of your hospital", "district": "Pick your District",
                  "address": "Enter Hospital Address",
                  "phone_number": "Enter emergency contact number of your hospital","oxygen_capacity":"Enter the total oxygen capacity of your hospital (in litres)"}


class FacilityCapacityCreationForm(ModelForm):
    class Meta:
        model = FacilityCapacity
        fields = ["room_type", "total_capacity", "current_capacity"]
        labels = {"room_type": "Bed Type", "total_capacity": "Total Capacity",
                  "current_capacity": "Currently Occupied"}


class DoctorsCountCreationForm(ModelForm):
    class Meta:
        model = HospitalDoctors
        fields = ["area", "count"]
        labels = {"area": "Area of specialization"}

care/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated, IsAdminUser


from care.users.api.serializers import UserSerializer

User = get_user_model()


class UserViewSet(viewsets.ModelViewSet):
    """
    A viewset for viewing and manipulating user instances.
    """

    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_permissions(self):
        if self.request.method == "POST":
            self.permission_classes = ()  # allows signup
        else:
            self.permission_classes = (IsAuthenticated,)
        return super().get_permissions()

    def get_queryset(self):
        if self.request.method == "DELETE" or self.request.method == "PUT":
            return self.queryset.filter(id=self.request.user.id)
        else:
            return self.queryset

    @action(detail=False, methods=["GET"])
    def getcurrentuser(self, request):
        return Response(
            status=status.HTTP_200_OK,
            data=self.serializer_class(request.user, context={"request": request}).data,
        )

care/templates/facility/facilities_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}Hospitals{% endblock %}



{% block content %}
<h1 class="text-2xl font-bold text-center my-4">{% trans " The Chief Ministers's office requests to know Live Data" %}</h1>
{% for i in data  %}
<div class="shadow-lg rounded overflow-hidden w-full p-3 my-4">
    <a href="{% url 'facility:facility-view' pk=i.id %}">
        <span class="hospital-title block text-4xl text-center">{{i.name}}</span>
        <h1 class="text-gray-700">Address : {{i.address}}</h1>
        <h1 class="text-gray-700">Phone : {{i.phone_number}}</h1>
        <h1 class="text-gray-700">District : {{i.get_district_display}}</h1>
        <button type="button" class="mx-auto careblock mt-4 btn btn-primary">View & Edit Details</button>

    </a>
</div>
{% endfor %}

{% endblock %}

care/templates/facility/facility_capacity_creation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}


{% block title %}Add Rooms{% endblock %}

{% block content %}

<h1 class="text-2xl font-bold text-center">{% trans "Enter Your Hospital's Capacity" %}</h1>
<p class="max-w-lg text-lg mt-3 text-gray-700 text-justify">The Chief Ministers's office request to know information about  total capacity and current Utlisation of Normal Beds, ICU Beds and Ventilators in your Hospital.
<br>
1. Normal Beds<br>
2. ICU Beds<br>
3. Ventilators</p>
<form class="form-horizontal" method="post" action="">
  {% csrf_token %}
  {% if duplicate %}
  <p class="max-w-lg text-lg mt-3 text-red-700 text-justify">The bed type you are trying to add has already been added to the hospital, Please pick a different bed type.</p>
  {% endif %}
  {% if validation_error %}
  <p class="max-w-lg text-lg mt-3 text-red-700 text-justify">Currently occupied number should be lesser than or equal to the total Capacity.</p>
  {% endif %}
  {{ form|crispy }}
  <p class="max-w-lg text-lg mt-3 text-gray-700 text-justify">
    <br>
    1. Save and Add information about another bed type.<br>
    2. Save the entered information and submit to the network<br>
    3. Cancel</p>
  <div class="control-group">
    <div class="controls md:flex md:justify-between">
      <button type="submit" name="addmore" class=" mt-4 btn btn-primary">Save & Enter more Information</button>
      <button type="submit" class="mt-4 btn btn-primary">Save & Submit</button>
      <a class=" mt-4 btn btn-primary" href="{% url 'facility:facility-doctor-count-create' pk=facility.id %}">Cancel</a>
    </div>
  </div>
</form>
{% endblock %}

care/templates/facility/facility_capacity_updation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{{facility.name}}{% endblock %}

{% block content %}
<h1 class="text-2xl font-bold text-center">{% trans "Edit Bed Capacity" %}</h1>
<form class="form-horizontal" method="post" action="">
  {% if duplicate %}
  <p class="max-w-lg text-lg mt-3 text-red-700 text-justify">Please Enter a Room Type that is not entered already</p>
  {% endif %}
  {% if validation_error %}
  <p class="max-w-lg text-lg mt-3 text-red-700 text-justify">Currently occupied number should be lesser than or equal to the total Capacity.</p>
  {% endif %}
  {% csrf_token %}
  {{ form|crispy }}
  <div class="control-group">
    <div class="controls mt-4">
      <button type="submit" class="btn btn-primary">UPDATE</button>
      <a class="btn btn-primary" href="{% url 'facility:facility-view' pk=facility.id %}">Cancel</a>
    </div>
  </div>
</form>
{% endblock %}

care/templates/facility/facility_creation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}Add Hospital{% endblock %}

{% block content %}
    <h1 class="text-2xl font-bold text-center">{% trans "Add Hospital" %}</h1>
    <form class="form-horizontal" method="post" action="">
  {% csrf_token %}
  {{ form|crispy }}
  <div class="control-group">
    <div class="controls">
      <button type="submit" class="mt-4 btn btn-primary w-full">Add Your Hospital Information</button>
    </div>
  </div>
</form>
{% endblock %}

care/templates/facility/facility_doctor_count_creation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}Add the number of doctors in different specialization{% endblock %}

{% block content %}

<h1 class="text-2xl font-bold text-center">{% trans "Add The Number Of Doctors In Different Specializations" %}</h1>
<form class="form-horizontal" method="post" action="">
  {% csrf_token %}
  {% if duplicate %}
  <p class="max-w-lg text-lg mt-3 text-red-700 text-justify">The area for which you are trying to add the count is already added, please edit it instead. </p>
  {% endif %}
  {{ form|crispy }}
  <div class="control-group">
    <div class="controls md:flex md:justify-between">
      <button type="submit" name="addmore" class="mt-4 btn btn-primary">Save and Add More Doctors</button>
      <button type="submit" class="mt-4 btn btn-primary">Save and Complete</button>
      <a class="mt-4 btn btn-primary" href="{% url 'facility:facility-view' pk=facility.id %}">Cancel</a>
    </div>
  </div>
</form>
{% endblock %}

care/templates/facility/facility_doctor_count_updation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}{{facility.name}}{% endblock %}

{% block content %}
<h1 class="text-2xl font-bold text-center">{% trans "Edit Doctor Count" %}</h1><form class="form-horizontal" method="post" action="">
  {% if duplicate %}
  <p class="max-w-lg text-lg mt-3 text-red-700 text-justify">Please enter an area that is not entered already</p>
  {% endif %}
  {% csrf_token %}
  {{ form|crispy }}
  <div class="control-group">
    <div class="controls mt-4">
      <button type="submit" class="btn btn-primary">UPDATE</button>
      <a class="btn btn-primary" href="{% url 'facility:facility-view' pk=facility.id %}">Cancel</a>
    </div>
  </div>
</form>
{% endblock %}

care/templates/facility/facility_updation.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block title %}Add Hospital{% endblock %}

{% block content %}
<h1 class="text-2xl font-bold text-center">{% trans "Edit Hospital" %}</h1>
<form class="form-horizontal" method="post" action="">
  {% csrf_token %}
  {{ form|crispy }}
  <div class="control-group">
    <div class="controls mt-4">
      <button type="submit" class="btn btn-primary">Update</button>
    </div>
  </div>
</form>
{% endblock %}

care/templates/facility/facility_view.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{facility.name}}{% endblock %}

{% block content %}
<div class="flex flex-wrap mb-3">
  <div class="w-full lg:w-2/3 mb-3">
    <span class="hospital-title block text-4xl mb-3">{{facility.name}}</span>
    <h1 class="text-gray-700">Address : {{facility.address}}</h1>
    <h1 class="text-gray-700">Phone : {{facility.phone_number}}</h1>
    <h1 class="text-gray-700">District : {{facility.get_district_display}}</h1>
    <h1 class="text-gray-700">Oxygen Capacity : {{facility.oxygen_capacity}} Litres</h1>
  </div>
  <div class="w-full lg:w-1/3 flex flex-col items-center pl-2">
    <a class="btn btn-primary m-2" href="{% url 'facility:facility-update' pk=facility.id %}"> Update Hospital Info</a>
    <a class="btn btn-primary m-2" href="{% url 'facility:facility-capacity-create' pk=facility.id %}"> Add More Bed Types</a>
    <a class="btn btn-primary m-2" href="{% url 'facility:facility-doctor-count-create' pk=facility.id %}"> Add More Doctor Types</a>
  </div>
</div>

<br>
<h2 class="pb-2"><strong>Bed Types</strong></h2>
<hr />
<div id="facilities" class="flex flex-wrap mt-3 justify-between">
  {% for i in capacities  %}
  <div id="facilityCard" class="shadow-lg rounded overflow-hidden w-full cardwidth md:w-1/2 sm:w-full mr-4 mb-5">
    <span class="room_type text-xl block p-3">{{i.get_room_type_display}}</span>
    <span class="capacity-qty block text-4xl text-center">{{i.current_capacity}}</span>
    <span class="label block text-center text-gray-600">Currently Occupied</span>
    <button class="careblock mx-auto my-4 bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow">
      <a href="{% url 'facility:facility-capacity-update' fpk=facility.id cpk=i.id %}"> EDIT </a> </button>
    <div class="footer bg-gray-900 px-3 py-3 text-center">
      <span class="text-white ">Total Capacity: {{i.total_capacity}}</span>
    </div>
  </div>
  {% endfor %}
</div>
<br><br>
<h2 class="pb-2 mt-5"><strong>Doctor Counts</strong></h2>
<hr />
<div id="doctors" class="flex flex-wrap mt-3 justify-between">
  {% for i in doctor_counts  %}
  <div id="doctorCard" class="shadow-lg rounded overflow-hidden w-full cardwidth md:w-1/2 sm:w-full mr-4 mb-5">
    <span class="qty p-4 block text-4xl text-center">{{i.count}}</span>
    <span class="label block text-center text-gray-600">{{i.get_area_display}} Doctors</span>
    <button class="careblock mx-auto my-4 bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow">
      <a href="{% url 'facility:facility-doctor-count-update' fpk=facility.id cpk=i.id %}"> EDIT </a>
     </button>

  </div>
  {% endfor %}
</div>
{% endblock %}